### ISSUE TITLE
Multiple dropdown being triggered at the sametime

### ISSUE THREAD

**Issue by kayue** [valor-software/ng2-select#31] opened 2016-02-01 16:28 UTC
If I have multiple instance on the same page, they will be triggered at the same time.

![screen shot 2016-02-02 at 12 27 36 am](https://cloud.githubusercontent.com/assets/193112/12723308/d3d0b570-c943-11e5-8a1f-8537166c34df.png)

**Comment by knifir** [comment] 2016-02-03 09:19
Duplicate of #22

**Closed** 2016-02-03 09:58 UTC
